version: 2
jobs:
  test:
    steps:
      - run: echo 'test'
  build:
    steps:
      - checkout
      - run: echo 'build'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
