version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0-browsers-legacy
    steps:
      - run: sudo npm install -g npm@latest
      - run: echo 'test'
  build:
    docker:
      - image: circleci/node:10.15.0-browsers-legacy
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: echo 'build'
      - run: echo npm install -g @angular-cli
      - run: npm install
      - run: ng build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
