version: 2
jobs:
  test:
    docker:
      - image: circleci/node: 10.15.0-browsers-legacy
    steps:
      - run: echo 'test'
  build:
    docker:
      - image: circleci/node: 10.15.0-browsers-legacy
    steps:
      - checkout
      - run: echo 'build'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
